#compdef goal
# Generated by `goal config zsh`. Source after compinit; no service mutations.

_goal_ids() {
    local -a candidates
    candidates=("${(@f)$(command goal __complete 2>/dev/null)}")
    [[ -n ${candidates[1]} ]] || return 1
    _describe -t goals 'goal (enabled / service state)' candidates
}

_goal_commands() {
    local -a subcommands
    subcommands=(
        'add:Register a goal'
        'remove:Unregister a stopped goal'
        'up:Start enabled goals'
        'down:Stop goals'
        'enable:Enable a goal; --now also starts it'
        'disable:Disable a goal; --now also stops it'
        'list:List goals and their state'
        'ls:List goals and their state'
        'tail:Show or follow a service log'
        'stats:Summarize outcomes and usage'
        'analysis:Inspect activity and failures'
        'config:Print shell integration'
        'help:Show command help'
    )
    _describe -t commands 'goal command' subcommands
}

_goal() {
    local curcontext="$curcontext" state line
    local -A opt_args
    local -a common
    common=(
        '(-h --help)'{-h,--help}'[Show help]'
        '--output=[Output format]:format:(tui plain pretty json)'
    )
    _arguments -C "${common[@]}" \
        '(-V --version)'{-V,--version}'[Show version]' \
        '1:command:->command' \
        '*::arguments:->args'
    case $state in
        command) _goal_commands ;;
        args)
            case $words[1] in
                add)
                    _arguments "${common[@]}" \
                        '--id=[Stable goal ID]:new ID:' \
                        '1:goal.toml or directory:_files'
                    ;;
                up)
                    _arguments "${common[@]}" \
                        '--foreground[Run attached to this terminal; requires a goal ID]' \
                        '1:goal:_goal_ids'
                    ;;
                down|remove)
                    _arguments "${common[@]}" '1:goal:_goal_ids'
                    ;;
                enable|disable)
                    _arguments "${common[@]}" \
                        '--now[Also start or stop the goal now]' '1:goal:_goal_ids'
                    ;;
                list|ls)
                    _arguments "${common[@]}" '--watch[Follow goal state and runtime events]'
                    ;;
                tail)
                    _arguments "${common[@]}" \
                        '(-f --follow)'{-f,--follow}'[Follow the service log]' \
                        '(-n --lines)'{-n,--lines}'[Existing log lines to show]:lines:(20 50 100 500)' \
                        '1:goal:_goal_ids'
                    ;;
                stats)
                    _arguments "${common[@]}" \
                        '--since=[Rolling duration]:duration:(1h 3h 12h 24h 7d)' '1:goal:_goal_ids'
                    ;;
                analysis)
                    _arguments "${common[@]}" \
                        '(--date)--since=[Rolling duration]:duration:(1h 3h 12h 24h 7d)' \
                        '(--since)--date=[Local calendar date]:date (YYYY-MM-DD):' \
                        '1:goal:_goal_ids'
                    ;;
                config)
                    _arguments "${common[@]}" '1:shell:(zsh)'
                    ;;
                help)
                    _arguments '1:command:_goal_commands'
                    ;;
            esac
            ;;
    esac
}

compdef _goal goal
